/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/user/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Аутентификация */
        post: operations["signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Разлогинить пользователя */
        get: operations["signOut"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить сессию */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/session/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Обновить токены */
        get: operations["refreshToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Изменить пароль */
        post: operations["changeUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/password/send-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отправить ссылку для восстановления пароля */
        post: operations["sendRecoveryPasswordLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/password/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Восстановить пароль */
        post: operations["recoveryUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить Партнера-Строителя пользователя */
        get: operations["getPartnerBySession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить Партнера-Строителя по ID */
        get: operations["getPartnerById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/uploaded-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить дату последней выгрузки партнеров */
        get: operations["getPartnersUploadedDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список партнеров */
        get: operations["getPartners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список партнеров для выбора */
        get: operations["getPartnersSelect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список новостей */
        get: operations["getNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить новость по ID */
        get: operations["getNewsById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список документов */
        get: operations["getDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список категорий документов */
        get: operations["getDocumentCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bulletins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список бюллетеней */
        get: operations["getBulletins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bulletins/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список категорий бюллетеней */
        get: operations["getBulletinCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список избранных документов/бюллетеней */
        get: operations["getUserFavorites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/favorites/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить документ/бюллетень в избранное */
        post: operations["addFavorite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/favorites/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить документ/бюллетень из избранного */
        delete: operations["removeFavorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Поиск документов/бюллетеней/новостей */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Форма обратной связи */
        post: operations["sendFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kpi/uploaded-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить дату последней выгрузки данных KPI */
        get: operations["getKpiUploadedDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kpi/employee-testing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить данные тестирования сотрудников */
        get: operations["getEmployeeTesting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kpi/employee-testing/uploaded-years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список годов, за которые были загружены данные тестирования сотрудников */
        get: operations["getEmployeeTestingUploadedYears"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kpi/lead-generation/uploaded-years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список годов, за которые были загружены данные лидогенерации */
        get: operations["getLeadGenerationUploadedYears"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kpi/lead-generation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить данные лидогенерации */
        get: operations["getLeadGeneration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kpi/lead-generation/quarter-passed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить количество пройденных лидов по кварталам */
        get: operations["getLeadGenerationQuarterPassed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/factory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о заводе Астрон */
        get: operations["getFactoryInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/factory/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список сотрудников завода Астрон */
        get: operations["getFactoryTeam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/academy/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список разделов академии */
        get: operations["getAcademySections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/academy/sections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о разделе академии */
        get: operations["getAcademySectionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/academy/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить этапы процесса продаж в Академии */
        get: operations["getAcademySales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/academy/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список проектов и отзывов */
        get: operations["getAcademyProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/academy/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о проекте */
        get: operations["getAcademyProjectById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/academy/webinars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список вебинаров */
        get: operations["getAcademyWebinars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/academy/webinars/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о вебинаре */
        get: operations["getAcademyWebinarById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/academy/benefits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список преимуществ */
        get: operations["getAcademyBenefits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/academy/benefits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о преимуществе */
        get: operations["getAcademyBenefitById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/academy/benefits/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список тегов преимуществ */
        get: operations["getAcademyBenefitTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** @example 1 */
            id: string;
            /** @example Королев */
            surname: string;
            /** @example Данил */
            name: string;
            /** @example Николаевич */
            patronymic?: string;
            /** @example dev@mail.ru */
            email: string;
            /** @example +79231665038 */
            phone: string;
            /** @example 123 */
            password: string;
            /**
             * @example manager
             * @enum {string}
             */
            role: "manager" | "employee" | "partner";
            tokenVersion: number;
            isBanned: boolean;
            favorites: string[];
            /** @example 1 */
            partnerId?: string;
        };
        Session: {
            /** @example dev@mail.ru */
            email: string;
            /** @example Королев */
            surname: string;
            /** @example Данил */
            name: string;
            /** @example Николаевич */
            patronymic?: string;
            /**
             * @example manager
             * @enum {string}
             */
            role: "manager" | "employee" | "partner";
            /** @example +79231665038 */
            phone: string;
            favorites: string[];
            /** @example 10 */
            favoriteProjects: number;
        };
        Partner: {
            /** @example 1 */
            id: string;
            /** @example NABUCCO Architecture & Construction */
            title: string;
            projects: {
                /** @example 23 */
                count: number;
                /** @example /link/to/projects */
                link: string;
                /** @example 6578 */
                implementedArea: number;
            };
            /** @example 12 */
            cooperationYears: number;
            /** @example /path/to/logo.svg */
            logo: string;
            /** @example /path/to/certificate.pdf */
            certificate?: string;
            sales: {
                /** @example 1000000 */
                total: number;
                /** @example 88 */
                percent: number;
            };
            booking: {
                /** @example 1000000 */
                total: number;
                /** @example 88 */
                percent: number;
            };
        };
        PartnerCard: {
            /** @example 1 */
            id: string;
            /** @example Партнер */
            title: string;
            projects: {
                /** @example 23 */
                count: number;
                /** @example /link/to/projects */
                link: string;
                /** @example 6578 */
                implementedArea: number;
            };
            /** @example 12 */
            cooperationYears: number;
            /** @example /path/to/logo.svg */
            logo: string;
            /** @example /path/to/certificate.pdf */
            certificate?: string;
        };
        PartnerInList: {
            /** @example 1 */
            id: string;
            /** @example Партнер */
            title: string;
            /** @example /path/to/logo.png */
            logo: string;
            sales: {
                /** @example 1000000 */
                total: number;
                /** @example 88 */
                percent: number;
            };
            booking: {
                /** @example 1000000 */
                total: number;
                /** @example 88 */
                percent: number;
            };
        };
        PartnerInSelect: {
            /** @example 1 */
            id: string;
            /** @example Партнер */
            title: string;
        };
        News: {
            /** @example 1 */
            id: string;
            /** @example Ключевая ставка достигла 30% */
            title: string;
            /** @example Деняк нет, но вы держитесь */
            description: string;
            img: components["schemas"]["Image"];
            content: {
                /** @example Текст новости */
                text: string;
                documents?: (components["schemas"]["Document"] | components["schemas"]["Bulletin"])[];
            };
            /**
             * Format: date-time
             * @example 2024-12-30T12:34:56Z
             */
            createdAt: string;
        };
        NewsInList: {
            /** @example 1 */
            id: string;
            /** @example Ключевая ставка достигла 30% */
            title: string;
            /** @example Деняк нет, но вы держитесь */
            description: string;
            img: components["schemas"]["Image"];
            /**
             * Format: date-time
             * @example 2024-12-30T12:34:56Z
             */
            createdAt: string;
        };
        Document: {
            /** @example 1 */
            id: string;
            /** @example Документ */
            title: string;
            file: {
                /** @example /path/to/file.pdf */
                url: string;
                /** @example 607232 */
                size: number;
            };
            category: components["schemas"]["DocumentCategory"];
            /**
             * Format: date-time
             * @example 2024-12-30T12:34:56Z
             */
            createdAt: string;
        };
        Bulletin: {
            /** @example 1 */
            id: string;
            /** @example Документ */
            title: string;
            file: {
                /** @example /path/to/file.pdf */
                url: string;
                /** @example 607232 */
                size: number;
            };
            category: components["schemas"]["DocumentCategory"];
            /**
             * Format: date-time
             * @example 2024-12-30T12:34:56Z
             */
            createdAt: string;
        };
        DocumentCategory: {
            /** @example 1 */
            id: string;
            /** @example Изменение цены */
            label: string;
            /** @example price-change */
            slug: string;
        };
        Favorite: components["schemas"]["Document"] | components["schemas"]["Bulletin"];
        SearchResult: {
            /** @example 1 */
            id: string;
            /** @example Ключевая ставка достигла 30% */
            title: string;
            /** @enum {string} */
            type: "news" | "document" | "bulletin";
            /** @example Деняк нет, но вы держитесь */
            description?: string;
            /** @example /path/to/file.pdf */
            fileUrl?: string;
        };
        FactoryTeam: {
            /** @example 1 */
            id: string;
            img: components["schemas"]["Image"];
            /** @example Генеральный директор */
            role: string;
            /** @example Ягодкин Помидорослав */
            title: string;
            /** @example +79000000000 */
            phone: string;
            /** @example email@astron.biz */
            email: string;
        };
        AcademySection: {
            /** @example 1 */
            id: string;
            /** @example Процесс продаж */
            title: string;
            /** @example Описание процесса продаж */
            description?: string;
            content: components["schemas"]["InfoBlock"][];
        };
        AcademySectionInList: {
            /** @example 1 */
            id: string;
            /** @example Процесс продаж */
            title: string;
            /** @example /path/to/bg-img.jpg */
            bgImg: string;
            /** @example /path/to/url */
            url?: string;
            /** @example <svg>...</svg> */
            icon?: string;
        };
        AcademySales: {
            /** @example New */
            title: string;
            /** @example Новый запрос на здание */
            description: string;
            /** @example new */
            slug: string;
            content: components["schemas"]["InfoBlock"][];
        };
        AcademyProject: {
            /** @example 1 */
            id: string;
            /** @example Проект */
            title: string;
            /** @example Описание проекта */
            description: string;
            img: components["schemas"]["Image"];
            content: components["schemas"]["InfoBlock"][];
        };
        AcademyProjectInList: {
            /** @example 1 */
            id: string;
            /** @example Проект */
            title: string;
            /** @example Описание проекта */
            description: string;
            img: components["schemas"]["Image"];
        };
        AcademyWebinar: {
            /** @example 1 */
            id: string;
            /** @example Вебинар */
            title: string;
            /** @example Описание вебинара */
            description: string;
            img: components["schemas"]["Image"];
            content: components["schemas"]["InfoBlock"][];
        };
        AcademyWebinarInList: {
            /** @example 1 */
            id: string;
            /** @example Вебинар */
            title: string;
            /** @example Описание вебинара */
            description: string;
            img: components["schemas"]["Image"];
        };
        AcademyBenefit: {
            /** @example 1 */
            id: string;
            /** @example Преимущество */
            title: string;
            /** @example Описание преимущества */
            description: string;
            img: components["schemas"]["Image"];
            tags: components["schemas"]["AcademyBenefitTag"][];
            content: components["schemas"]["InfoBlock"][];
        };
        AcademyBenefitInList: {
            /** @example 1 */
            id: string;
            /** @example Преимущество */
            title: string;
            /** @example Описание преимущества */
            description: string;
            img: components["schemas"]["Image"];
            tags: components["schemas"]["AcademyBenefitTag"][];
        };
        AcademyBenefitTag: {
            /** @example 1 */
            id: string;
            /** @example Соответствие техническим требованиям */
            label: string;
            /** @example technical-requirements */
            slug: string;
        };
        InfoBlock: components["schemas"]["SectionBlock"] | components["schemas"]["SeparatorBlock"] | components["schemas"]["HtmlBlock"];
        SectionBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "section";
            /** @example Заголовок */
            title: string;
            text?: string;
            media?: components["schemas"]["MediaBlock"];
            documents?: components["schemas"]["Document"][];
        };
        SeparatorBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "separator";
        };
        HtmlBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "html";
            content: string;
        };
        MediaBlock: components["schemas"]["ImageBlock"] | components["schemas"]["VideoBlock"];
        ImageBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
            /** @example /path/to/img.jpg */
            src: string;
            /** @example Картинка завода Астрон */
            alt?: string;
        };
        VideoBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "video";
            /** @example /path/to/video.mp4 or https://www.youtube.com/watch?v=dQw4w9WgXcQ */
            src: string;
            /** @example /path/to/thumbnail.jpg */
            thumbnail: string;
            /** @example Видео о заводе Астрон */
            alt?: string;
        };
        Image: {
            /** @example /path/to/img.jpg */
            src: string;
            /** @example Картинка завода Астрон */
            alt?: string;
        };
        Video: {
            /** @example /path/to/video.mp4 or https://www.youtube.com/watch?v=dQw4w9WgXcQ */
            src: string;
            /** @example /path/to/thumbnail.jpg */
            thumbnail: string;
            /** @example Видео о заводе Астрон */
            alt?: string;
        };
        EmployeeTesting: {
            /** @example 1 */
            id: string;
            /** @example Специалист по монтажу */
            test: string;
            /** @example Иванов-Петров Кладиславослав */
            name: string;
            /** @example 81 */
            result: number;
        };
        LeadGeneration: {
            /** @example 1 */
            id: string;
            project: {
                /** @example 1 */
                id: string;
                /** @example Проект */
                name: string;
            };
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00Z
             */
            fixedAt: string;
        };
        LeadGenerationQuarterPassed: {
            /** @example 1 */
            idx: number;
            /** @example 5 */
            passedCount: number;
        };
        Error: {
            message: string;
        };
        Success: {
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example dev@mail.ru */
                    login: string;
                    /** @example password */
                    password: string;
                    remember?: boolean;
                };
            };
        };
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        user: components["schemas"]["Session"];
                    };
                };
            };
            /** @description Ошибка ввода данных */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Пользователь забанен */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Ошибка авторизации */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description Refresh Token с клиента */
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                    };
                };
            };
            /** @description Ошибка авторизации */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    changeUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    password: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Пароль успешно изменен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            /** @description Введен неверный пароль */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    sendRecoveryPasswordLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    email: string;
                };
            };
        };
        responses: {
            /** @description Ссылка для восстановления пароля отправлена на почту */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            /** @description Пользователь с таким email не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Ошибка при отправке письма */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    recoveryUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    password: string;
                    token: string;
                };
            };
        };
        responses: {
            /** @description Пароль успешно изменен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            /** @description Время на восстановление пароля по этой ссылке истекло */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Пользователь с таким ID токена не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPartnerBySession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerCard"];
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPartnerById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID партнера */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerCard"];
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Партнер-Строитель не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPartnersUploadedDate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPartners: {
        parameters: {
            query?: {
                /** @description Сортировка партнеров */
                sort?: "asc-sales" | "desc-sales" | "asc-bookings" | "desc-bookings" | "asc-name" | "desc-name";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerInList"][];
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPartnersSelect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerInSelect"][];
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getNews: {
        parameters: {
            query?: {
                /** @description Номер страницы */
                page?: number;
                /** @description Количество новостей на странице */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["NewsInList"][];
                        /** @example 1 */
                        nextPage: number;
                    };
                };
            };
        };
    };
    getNewsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID новости */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["News"];
                };
            };
            /** @description Новость с таким ID не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDocuments: {
        parameters: {
            query?: {
                /** @description Номер страницы */
                page?: number;
                /** @description Количество документов на странице */
                limit?: number;
                /** @description Категория документа */
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Document"][];
                        /** @example 10 */
                        totalPages: number;
                        /** @example 1 */
                        nextPage: number;
                    };
                };
            };
        };
    };
    getDocumentCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentCategory"][];
                };
            };
        };
    };
    getBulletins: {
        parameters: {
            query?: {
                /** @description Номер страницы */
                page?: number;
                /** @description Количество бюллетеней на странице */
                limit?: number;
                /** @description Категория бюллетеня */
                category?: string;
                /** @description Сортировка бюллетеней */
                sort?: "latest" | "oldest";
                /** @description Дата начала периода */
                fromDate?: string;
                /** @description Дата конца периода */
                toDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Bulletin"][];
                        /** @example 10 */
                        totalPages: number;
                        /** @example 1 */
                        nextPage: number;
                    };
                };
            };
        };
    };
    getBulletinCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentCategory"][];
                };
            };
        };
    };
    getUserFavorites: {
        parameters: {
            query?: {
                /** @description Номер страницы */
                page?: number;
                /** @description Количество документов на странице */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Favorite"][];
                        /** @example 1 */
                        nextPage: number;
                        /** @example 10 */
                        totalPages: number;
                    };
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    id: string;
                };
            };
        };
        responses: {
            /** @description Документ/бюллетень успешно добавлен в избранное */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Документ/бюллетень с таким ID не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    removeFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    id: string;
                };
            };
        };
        responses: {
            /** @description Документ/бюллетень успешно удален из избранного */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Документ/бюллетень с таким ID не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Запрос для поиска */
                query: string;
                /** @description Номер страницы */
                page?: number;
                /** @description Количество результатов на странице */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SearchResult"][];
                        /** @example 10 */
                        totalPages: number;
                        /** @example 300 */
                        totalResults: number;
                        /** @example 1 */
                        nextPage: number;
                    };
                };
            };
        };
    };
    sendFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example Иванов Иван Иванович */
                    fio: string;
                    /** @example +79231665038 */
                    phone: string;
                    /** @example Хороший сайт */
                    message: string;
                    /** @example true */
                    privacy: boolean;
                    /** @example true */
                    personalData: boolean;
                };
            };
        };
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    getKpiUploadedDate: {
        parameters: {
            query?: {
                /** @description ID партнёра */
                partnerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Партнёр не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEmployeeTesting: {
        parameters: {
            query: {
                /** @description Год */
                year: string;
                /** @description ID партнёра */
                partnerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EmployeeTesting"][];
                        /**
                         * Format: date-time
                         * @example 2024-01-01T00:00:00.000Z
                         */
                        uploadedAt: string;
                        /**
                         * Format: date-time
                         * @example 2024-01-01T00:00:00.000Z
                         */
                        updatedAt: string;
                    };
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Партнёр не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEmployeeTestingUploadedYears: {
        parameters: {
            query?: {
                /** @description ID партнёра */
                partnerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Партнёр не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLeadGenerationUploadedYears: {
        parameters: {
            query?: {
                /** @description ID партнёра */
                partnerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Партнёр не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLeadGeneration: {
        parameters: {
            query: {
                /** @description Год */
                year: string;
                /** @description ID партнёра */
                partnerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadGeneration"];
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Партнёр не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLeadGenerationQuarterPassed: {
        parameters: {
            query: {
                /** @description Год */
                year: string;
                /** @description ID партнёра */
                partnerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadGenerationQuarterPassed"];
                };
            };
            /** @description Пользователь не авторизован */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Партнёр не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFactoryInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example <p>Текст о заводе Астрон</p> */
                        text: string;
                        img: components["schemas"]["Image"];
                        video: components["schemas"]["Video"];
                        document: components["schemas"]["Document"];
                    };
                };
            };
        };
    };
    getFactoryTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactoryTeam"][];
                };
            };
        };
    };
    getAcademySections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademySectionInList"][];
                };
            };
        };
    };
    getAcademySectionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID раздела */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademySection"];
                };
            };
            /** @description Раздел не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAcademySales: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademySales"][];
                };
            };
        };
    };
    getAcademyProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademyProjectInList"][];
                };
            };
        };
    };
    getAcademyProjectById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID проекта */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademyProject"];
                };
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAcademyWebinars: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademyWebinarInList"][];
                };
            };
        };
    };
    getAcademyWebinarById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID вебинара */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademyWebinar"];
                };
            };
            /** @description Вебинар не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAcademyBenefits: {
        parameters: {
            query?: {
                /** @description Номер страницы */
                page?: number;
                /** @description Количество преимуществ на странице */
                limit?: number;
                /** @description Теги преимуществ */
                tags?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AcademyBenefitInList"][];
                        /** @example 1 */
                        nextPage: number;
                        /** @example 100 */
                        totalResults: number;
                    };
                };
            };
        };
    };
    getAcademyBenefitById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID преимущества */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademyBenefit"];
                };
            };
            /** @description Преимущество не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAcademyBenefitTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademyBenefitTag"][];
                };
            };
        };
    };
}
